### ISSUE TITLE
Support for WDPE 2.0.0

### ISSUE THREAD

**Issue by Flonja** [alvin0319/CustomItemLoader-WDPE#1]
Title says the problem.

**Comment by alvin0319** [comment]
The latest commit should fix the issue, but I didn't test it since I have no servers to test. Feel free to test it and open an issue if there are any issues.

*To build jar, use `./gradlew shadowJar`*

**Comment by Flonja** [comment]
```
java.lang.IllegalArgumentException: Packet class already registered
        at org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:132) ~[Waterdog.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec$Builder.registerPacket(BedrockCodec.java:126) ~[Waterdog.jar:?]
        at dev.minjae.customitemloader.wdpe.Loader$onEnable$2.updateCodec(Loader.kt:23) ~[?:?]
        at dev.waterdog.waterdogpe.network.protocol.ProtocolCodecs.buildCodec(ProtocolCodecs.java:136) ~[Waterdog.jar:?]
        at dev.waterdog.waterdogpe.ProxyServer.boot(ProxyServer.java:212) ~[Waterdog.jar:?]
        at dev.waterdog.waterdogpe.ProxyServer.<init>(ProxyServer.java:193) ~[Waterdog.jar:?]
        at dev.waterdog.waterdogpe.WaterdogPE.main(WaterdogPE.java:78) ~[Waterdog.jar:?]
```
